# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'NSUserDefaults-Subscripting-Example' do

pod 'NSUserDefaults+Subscripting', :path => '../'

end

target 'NSUserDefaults-Subscripting-ExampleTests' do

end

